server:
  port: 8080

spring:

  application:
    name: KnowledgeSphere

  datasource:
    url: jdbc:postgresql://localhost:5432/knowledge_sphere
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  ai:

    ollama:

      base-url: http://localhost:11434

      chat:

        options:

          model: qwen2.5:7b

          temperature: 0.2

    vectorstore:

      pgvector:

        initialize-schema: true

jwt:

  secret: CHANGE_THIS_TO_64_CHARACTER_SECRET

  expiration: 86400000

cloudinary:

  cloud-name: YOUR_CLOUD_NAME

  api-key: YOUR_API_KEY

  api-secret: YOUR_API_SECRET

springdoc:

  swagger-ui:

    path: /swagger-ui.html